{% set name = "lineax" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lineax-{{ version }}.tar.gz
  sha256: 5f1a8f060142af2cdbf7d66b99e8d3071c3aa734b677df6339df4b4c4c0554d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - equinox >=0.11.10
    - jax >=0.6.1
    - jaxtyping >=0.2.24
    - typing_extensions >=4.5.0

test:
  imports:
    - lineax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/patrick-kidger/lineax
  summary: Linear solvers in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
